name: Build single exes that references Grpc

on: [push]

jobs:
  binary-win:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-dotnet@v1.0.2
      with:
        dotnet-version: "3.0.100"
    - name: build
      run: |
        mkdir $env:HOME\bin-x86;
        mkdir $env:HOME\bin-x64;
        mkdir $env:HOME\bin-x86-untrimmed;
        mkdir $env:HOME\bin-x64-untrimmed;
        mkdir $env:HOME\bin-x86-unpacked;
        mkdir $env:HOME\bin-x64-unpacked;
        cd ConsoleAppUsingGrpc;
        dotnet restore;
        dotnet publish -r win-x86 -c Release -o $env:HOME\bin-x86\ ConsoleAppUsingGrpc.csproj /p:PublishSingleFile=true /p:PublishTrimmed=true;
        dotnet publish -r win-x64 -c Release -o $env:HOME\bin-x64\ ConsoleAppUsingGrpc.csproj /p:PublishSingleFile=true /p:PublishTrimmed=true;
        dotnet publish -r win-x86 -c Release -o $env:HOME\bin-x86-untrimmed\ ConsoleAppUsingGrpc.csproj /p:PublishSingleFile=true;
        dotnet publish -r win-x64 -c Release -o $env:HOME\bin-x64-untrimmed\ ConsoleAppUsingGrpc.csproj /p:PublishSingleFile=true;
        dotnet publish -r win-x86 -c Release -o $env:HOME\bin-x86-unpacked\ ConsoleAppUsingGrpc.csproj;
        dotnet publish -r win-x64 -c Release -o $env:HOME\bin-x64-unpacked\ ConsoleAppUsingGrpc.csproj;
      shell: pwsh
    # Upload
    - uses: actions/upload-artifact@master
      with:
        name: bin-x86
        path: D:\bin-x86 
    - uses: actions/upload-artifact@master
      with:
        name: bin-x64
        path: D:\bin-x64 
    - uses: actions/upload-artifact@master
      with:
        name: bin-x86-untrimmed
        path: D:\bin-x86-untrimmed 
    - uses: actions/upload-artifact@master
      with:
        name: bin-x64-untrimmed
        path: D:\bin-x64-untrimmed 
    - uses: actions/upload-artifact@master
      with:
        name: bin-x86-unpacked
        path: D:\bin-x86-unpacked
    - uses: actions/upload-artifact@master
      with:
        name: bin-x64-unpacked
        path: D:\bin-x64-unpacked
    # Tests
    - name: Test bin-x86
      run: |
        D:\bin-x86\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
    - name: Test bin-x64
      run: |
        D:\bin-x64\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
    - name: Test bin-x86-untrimmed
      run: |
        D:\bin-x86-untrimmed\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
    - name: Test bin-x64-untrimmed
      run: |
        D:\bin-x64-untrimmed\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
    - name: Test bin-x86-unpacked
      run: |
        D:\bin-x86-unpacked\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
    - name: Test bin-x64-unpacked
      run: |
        D:\bin-x64-unpacked\ConsoleAppUsingGrpc.exe
      shell: pwsh
      continue-on-error: true
